export const yueduOCR = {
    "id": null,
    "stuID": null,
    "category": "yuedu",
    "problem": null,
    "field": null,
    "answer": null,
    "sonProID": null,
    "insertTime": null,
    "score": 0,
    "choiceNum": 0,
    "level": 0,
    "knowledge": null,
    "choice1": null,
    "choice2": null,
    "choice3": null,
    "choice4": null,
    "content": "ant-housing, you couldn't get listed and admitted into the hospital,\" Kaufman said. She leaned that for the\n nearly 110,000 people in the US waiting for a lifesaving organ transplant, it was not just a matter of adding your name to the list. Patients must be financially secure and be able to afford transportation. What's more, they must find accommodations near their transplant hospital: Kaufman runs two housing locations, which allows the patients to remain close to their transplant hospital during the period of their aftercare, typically about three months at no cost.\n Her organization also helps donor families, which she thinks makes the whole circle complete. \"One organ donor can save eight lives and then there's tissue and skin and eyes and blood vessels(血管) and so many other things,\" Kaufman said. \"The donor is the whole story. Without the donor, there are no transplant centers, no transplant surgeons, no me. In my eyes, the donors are the heroes.\"\n To date, Ava's Heart has helped nearly 90 families with burial costs for their loved ones whose organs have saved countless lives. Kaufman also works closely with those who receive donations to build relationships with donor families and spread awareness about the importance of organ donation.",
    "esID": "9336fdeb-d1f9-4aa4-bc29-055fc73c9115",
    "stuAnswer": "",
    "isRight": false,
    "compCommentID": null,
    "transCommentID": null,
    "translateDetail": null,
    "compositionDetail": null,
    "stuScore": 0,
    "falseReasonID": null,
    "falseReason": null,
    "aiComment": "",
    "cuoTiList": [
        {
            "id": null,
            "stuID": null,
            "category": null,
            "problem": "Why did Kaufman take about her memory in Paragraph 1?",
            "field": null,
            "answer": null,
            "sonProID": null,
            "insertTime": null,
            "score": 0,
            "choiceNum": 4,
            "level": 0,
            "knowledge": null,
            "choice1": "A. To illustrate the significance of life.",
            "choice2": "B. To recal her plain and boring days.",
            "choice3": "C. To indicate her motivation for paying back.",
            "choice4": "D. To confirm her enthusiasm for the profession.",
            "content": null,
            "esID": null,
            "stuAnswer": null,
            "isRight": false,
            "compCommentID": null,
            "transCommentID": null,
            "translateDetail": null,
            "compositionDetail": null,
            "stuScore": 0,
            "falseReasonID": null,
            "falseReason": null,
            "aiComment": null,
            "cuoTiList": null,
            "sonExercise": null,
            "userComment": null,
            "redoNum": null,
            "redoID": null,
            "needRedo": null,
            "questionID": null,
            "single": false,
            "right": false
        },
        {
            "id": null,
            "stuID": null,
            "category": null,
            "problem": "For a transplant patient, admission into the hospital requires the following EXCEPT",
            "field": null,
            "answer": null,
            "sonProID": null,
            "insertTime": null,
            "score": 0,
            "choiceNum": 4,
            "level": 0,
            "knowledge": null,
            "choice1": "A. health insurance",
            "choice2": "B. nearby housing",
            "choice3": "C. financial security",
            "choice4": "D. afford transportation",
            "content": null,
            "esID": null,
            "stuAnswer": null,
            "isRight": false,
            "compCommentID": null,
            "transCommentID": null,
            "translateDetail": null,
            "compositionDetail": null,
            "stuScore": 0,
            "falseReasonID": null,
            "falseReason": null,
            "aiComment": null,
            "cuoTiList": null,
            "sonExercise": null,
            "userComment": null,
            "redoNum": null,
            "redoID": null,
            "needRedo": null,
            "questionID": null,
            "single": false,
            "right": false
        },
        {
            "id": null,
            "stuID": null,
            "category": null,
            "problem": "Which of the following best describes Kaufman?",
            "field": null,
            "answer": null,
            "sonProID": null,
            "insertTime": null,
            "score": 0,
            "choiceNum": 4,
            "level": 0,
            "knowledge": null,
            "choice1": "A. Brave and caring.",
            "choice2": "B. Grateful and warm-hearted.",
            "choice3": "C. Considerate and hardworking.",
            "choice4": "D. Sympathetic and easy-going.",
            "content": null,
            "esID": null,
            "stuAnswer": null,
            "isRight": false,
            "compCommentID": null,
            "transCommentID": null,
            "translateDetail": null,
            "compositionDetail": null,
            "stuScore": 0,
            "falseReasonID": null,
            "falseReason": null,
            "aiComment": null,
            "cuoTiList": null,
            "sonExercise": null,
            "userComment": null,
            "redoNum": null,
            "redoID": null,
            "needRedo": null,
            "questionID": null,
            "single": false,
            "right": false
        },
        {
            "id": null,
            "stuID": null,
            "category": null,
            "problem": "What message does the text mainly convey?",
            "field": null,
            "answer": null,
            "sonProID": null,
            "insertTime": null,
            "score": 0,
            "choiceNum": 4,
            "level": 0,
            "knowledge": null,
            "choice1": "A. It's better to give than to receive.",
            "choice2": "B The blessed bear the heart of giving.",
            "choice3": "C. Health matters much more than wealth.",
            "choice4": "D. Volunteering makes the world a better place.",
            "content": null,
            "esID": null,
            "stuAnswer": null,
            "isRight": false,
            "compCommentID": null,
            "transCommentID": null,
            "translateDetail": null,
            "compositionDetail": null,
            "stuScore": 0,
            "falseReasonID": null,
            "falseReason": null,
            "aiComment": null,
            "cuoTiList": null,
            "sonExercise": null,
            "userComment": null,
            "redoNum": null,
            "redoID": null,
            "needRedo": null,
            "questionID": null,
            "single": false,
            "right": false
        }
    ],
    "sonExercise": null,
    "userComment": null,
    "redoNum": null,
    "redoID": null,
    "needRedo": null,
    "questionID": null,
    "single": false,
    "right": false
}

export const xuanzeOCR = {
    "id": null,
    "stuID": null,
    "category": "xuanze",
    "problem": "The professor walked onto the platform and seated himself in a chair,  for answering( )questions.",
    "field": null,
    "answer": null,
    "sonProID": null,
    "insertTime": null,
    "score": 0,
    "choiceNum": 4,
    "level": 0,
    "knowledge": null,
    "choice1": "had prepared",
    "choice2": "being prepared",
    "choice3": "preparing",
    "choice4": "prepared",
    "content": null,
    "esID": "eb3ac92f-826f-43a2-b20d-dfd9f5191e88",
    "stuAnswer": "",
    "isRight": false,
    "compCommentID": null,
    "transCommentID": null,
    "translateDetail": null,
    "compositionDetail": null,
    "stuScore": 0,
    "falseReasonID": null,
    "falseReason": null,
    "aiComment": "",
    "cuoTiList": null,
    "sonExercise": null,
    "userComment": null,
    "redoNum": null,
    "redoID": null,
    "needRedo": null,
    "questionID": null,
    "single": false,
    "right": false
}

export const zuowenOCR = {
    "id": null,
    "stuID": null,
    "category": "zuowen",
    "problem": null,
    "field": null,
    "answer": null,
    "sonProID": null,
    "insertTime": null,
    "score": 0,
    "choiceNum": 0,
    "level": 0,
    "knowledge": null,
    "choice1": null,
    "choice2": null,
    "choice3": null,
    "choice4": null,
    "content": " 作文题目：《社交媒体对社会的影响》\n  近年来，社交媒体平台已成为我们日常生活中不可或缺的一部分，影响着我们的交流方式、互动方 式以及对周围世界的认知。请就社交媒体对社会的各种影响展开讨论。考虑其正面和负面效应，并 提供例证支持你的论点。此外，探讨社交媒体在塑造文化、政治、人际关系以及个体幸福感方面的 作用。最后，讨论减轻负面影响、最大程度发挥社交媒体利益的潜在策略。\n  ",
    "esID": "45fbb71d-42d6-4952-930b-7856f183fc61",
    "stuAnswer": "",
    "isRight": false,
    "compCommentID": null,
    "transCommentID": null,
    "translateDetail": null,
    "compositionDetail": null,
    "stuScore": 0,
    "falseReasonID": null,
    "falseReason": null,
    "aiComment": "",
    "cuoTiList": null,
    "sonExercise": null,
    "userComment": null,
    "redoNum": null,
    "redoID": null,
    "needRedo": null,
    "questionID": null,
    "single": false,
    "right": false
}

export const fanyiOCR = {
    "id": null,
    "stuID": null,
    "category": "fanyi",
    "problem": null,
    "field": null,
    "answer": null,
    "sonProID": null,
    "insertTime": null,
    "score": 0,
    "choiceNum": 0,
    "level": 0,
    "knowledge": null,
    "choice1": null,
    "choice2": null,
    "choice3": null,
    "choice4": null,
    "content": " 题目：请将以下长文本翻译成中文：\n  \"Artificial intelligence (Al) is rapidly transforming various aspects of our lives, from healthcare and finance to transportation and entertainment. With Al, machines are able to perform tasks that traditionally required human intelligence, such as recognizing speech, interpreting images, and making decisions. As Al technology continues to advance, it has the potential to revolutionize industries and improve efficiency in countless ways. However, Al also raises important ethical and societal questions, such as concerns about job displacement, privacy, and algorithmic bias.\n  Therefore, it is crucial for policymakers, researchers, and the public to engage in discussions about the responsible development and use of Al to ensure that its benefits are maximized while minimizing potential risks.\"\n  ",
    "esID": "7a1046db-f8c8-4d61-994d-c6e4aeb92ec8",
    "stuAnswer": "",
    "isRight": false,
    "compCommentID": null,
    "transCommentID": null,
    "translateDetail": null,
    "compositionDetail": null,
    "stuScore": 0,
    "falseReasonID": null,
    "falseReason": null,
    "aiComment": "",
    "cuoTiList": null,
    "sonExercise": null,
    "userComment": null,
    "redoNum": null,
    "redoID": null,
    "needRedo": null,
    "questionID": null,
    "single": false,
    "right": false
}


