//作文题
export const currentOCR = {
	OCRResult: '',
	backToNewQues: false,
	mode: 'zuowen'
}
//阅读识题结果
export const tmpOCRResult1 = [
    {
        "id": 78,
        "category": "yuedu",
        "problem": "Why did Kaufman take about her memory in Paragraph 1?",
        "answer": "A",
        "sonProID": "79,80,81",
        "score": 3,
        "choiceNum": 4,
        "level": 0,
        "field": "医学",
        "knowledgeIDs": null,
        "choice1": "A. To illustrate the significance of life.",
        "choice2": "B. To recall her plain and boring days.",
        "choice3": "C. To indicate her motivation for paying back.",
        "choice4": "D. To confirm her enthusiasm for the profession.",
        "content": `Managing Your Emotions
		
What makes me angry? Mostly, I hate when someone tries to make someone else feel bad. I have to admit that once, when I was really angry, I actually called names. 

I regretted doing this afterwards, but not full heartedly because I think I was provoked in that situation. The most positive way of dealing with anger is talking about the problem. I talk to someone who listens, or I'll write my thoughts down on paper. Learning how to deal with anger as you're growing up is so important. When you're younger, you might yell, or cry when you're angry, but as you get older,you're expected to handle your emotions much better. Learning to control your emotion now will prevent you from doing something that you'll regret later on in life!

A bank robber stole a lot of money. He was caught and sent to prison, but the money was never found. When he came out of prison, they watched him to see what he would do. Here is the detective, reporting to the inspector. "Yes, sir, I found Johnny . I followed him all around the town, but frankly, I couldn't make anything out of what he bought. 

Here's the list. "shirt , heavy crowbar, box of chocolates , shovel, heavy hammer, bunch of flowers .The inspector said, "Good. That helps me a lot. Do you remember how we watched him helping his neighbour, old Mrs. Judson to cover her backyard with cement?`,
        "stuAnswer": null,
        "aiComment": null,
        "falseReason": null,
        "userComment": null,
        "sonExercise": [
            {
                "id": 78,
                "category": null,
                "problem": "Why did Kaufman take about her memory in Paragraph 1?",
                "answer": "A",
                "sonProID": null,
                "score": 0,
                "choiceNum": 4,
                "level": 0,
                "field": null,
                "knowledgeIDs": null,
                "choice1": "A. To illustrate the significance of life.",
                "choice2": "B. To recall her plain and boring days.",
                "choice3": "C. To indicate her motivation for paying back.",
                "choice4": "D. To confirm her enthusiasm for the profession.",
                "content": null,
                "stuAnswer": null,
                "aiComment": null,
                "falseReason": null,
                "userComment": null,
                "sonExercise": null,
                "cuoTiList": null,
                "esID": null,
                "single": false,
                "existed": true
            },
            {
                "id": 79,
                "category": "yuedu",
                "problem": "For a transplant patient, admission into the hospital requires the following EXCEPT",
                "answer": "B",
                "sonProID": null,
                "score": 3,
                "choiceNum": 4,
                "level": 0,
                "field": null,
                "knowledgeIDs": null,
                "choice1": "A. health insurance",
                "choice2": "B. nearby housing",
                "choice3": "C. financial security",
                "choice4": "D. afford transportation",
                "content": null,
                "stuAnswer": null,
                "aiComment": null,
                "falseReason": null,
                "userComment": null,
                "sonExercise": null,
                "cuoTiList": null,
                "esID": null,
                "single": false,
                "existed": true
            },
            {
                "id": 80,
                "category": "yuedu",
                "problem": "Which of the following best describes Kaufman?",
                "answer": "D",
                "sonProID": null,
                "score": 3,
                "choiceNum": 4,
                "level": 0,
                "field": null,
                "knowledgeIDs": null,
                "choice1": "A. Brave and caring",
                "choice2": "B. Grateful and warm-hearted.",
                "choice3": "C. Considerate and hardworking.",
                "choice4": "D. Sympathetic and easy-going.",
                "content": null,
                "stuAnswer": null,
                "aiComment": null,
                "falseReason": null,
                "userComment": null,
                "sonExercise": null,
                "cuoTiList": null,
                "esID": null,
                "single": false,
                "existed": true
            },
            {
                "id": 81,
                "category": "yuedu",
                "problem": "What message does the text mainly convey?",
                "answer": "B",
                "sonProID": null,
                "score": 3,
                "choiceNum": 4,
                "level": 0,
                "field": null,
                "knowledgeIDs": null,
                "choice1": "A. It's better to give than to receive.",
                "choice2": "B. The blessed bear the heart of giving.",
                "choice3": "C. Health matters much more than wealth.",
                "choice4": "D. Volunteering makes the world a better place.",
                "content": null,
                "stuAnswer": null,
                "aiComment": null,
                "falseReason": null,
                "userComment": null,
                "sonExercise": null,
                "cuoTiList": null,
                "esID": null,
                "single": false,
                "existed": true
            }
        ],
        "cuoTiList": null,
        "esID": "dfe72ac2-0e2e-4e2f-930c-c5d80a0f4118",
        "single": false,
        "existed": true
    },
    {
            "id": 78,
            "category": "yuedu",
            "problem": "Why did Kaufman take about her memory in Paragraph 1?",
            "answer": "A",
            "sonProID": "79,80,81",
            "score": 3,
            "choiceNum": 4,
            "level": 0,
            "field": "医学",
            "knowledgeIDs": null,
            "choice1": "A. To illustrate the significance of life.",
            "choice2": "B. To recall her plain and boring days.",
            "choice3": "C. To indicate her motivation for paying back.",
            "choice4": "D. To confirm her enthusiasm for the profession.",
            "content": `Managing Your Emotions
    		
    What makes me angry? Mostly, I hate when someone tries to make someone else feel bad. I have to admit that once, when I was really angry, I actually called names. 
    
    I regretted doing this afterwards, but not full heartedly because I think I was provoked in that situation. The most positive way of dealing with anger is talking about the problem. I talk to someone who listens, or I'll write my thoughts down on paper. Learning how to deal with anger as you're growing up is so important. When you're younger, you might yell, or cry when you're angry, but as you get older,you're expected to handle your emotions much better. Learning to control your emotion now will prevent you from doing something that you'll regret later on in life!
    
    A bank robber stole a lot of money. He was caught and sent to prison, but the money was never found. When he came out of prison, they watched him to see what he would do. Here is the detective, reporting to the inspector. "Yes, sir, I found Johnny . I followed him all around the town, but frankly, I couldn't make anything out of what he bought. 
    
    Here's the list. "shirt , heavy crowbar, box of chocolates , shovel, heavy hammer, bunch of flowers .The inspector said, "Good. That helps me a lot. Do you remember how we watched him helping his neighbour, old Mrs. Judson to cover her backyard with cement?`,
            "stuAnswer": null,
            "aiComment": null,
            "falseReason": null,
            "userComment": null,
            "sonExercise": [
                {
                    "id": 78,
                    "category": null,
                    "problem": "Why did Kaufman take about her memory in Paragraph 1?",
                    "answer": "A",
                    "sonProID": null,
                    "score": 0,
                    "choiceNum": 4,
                    "level": 0,
                    "field": null,
                    "knowledgeIDs": null,
                    "choice1": "A. To illustrate the significance of life.",
                    "choice2": "B. To recall her plain and boring days.",
                    "choice3": "C. To indicate her motivation for paying back.",
                    "choice4": "D. To confirm her enthusiasm for the profession.",
                    "content": null,
                    "stuAnswer": null,
                    "aiComment": null,
                    "falseReason": null,
                    "userComment": null,
                    "sonExercise": null,
                    "cuoTiList": null,
                    "esID": null,
                    "single": false,
                    "existed": true
                },
                {
                    "id": 79,
                    "category": "yuedu",
                    "problem": "For a transplant patient, admission into the hospital requires the following EXCEPT",
                    "answer": "B",
                    "sonProID": null,
                    "score": 3,
                    "choiceNum": 4,
                    "level": 0,
                    "field": null,
                    "knowledgeIDs": null,
                    "choice1": "A. health insurance",
                    "choice2": "B. nearby housing",
                    "choice3": "C. financial security",
                    "choice4": "D. afford transportation",
                    "content": null,
                    "stuAnswer": null,
                    "aiComment": null,
                    "falseReason": null,
                    "userComment": null,
                    "sonExercise": null,
                    "cuoTiList": null,
                    "esID": null,
                    "single": false,
                    "existed": true
                },
                {
                    "id": 80,
                    "category": "yuedu",
                    "problem": "Which of the following best describes Kaufman?",
                    "answer": "D",
                    "sonProID": null,
                    "score": 3,
                    "choiceNum": 4,
                    "level": 0,
                    "field": null,
                    "knowledgeIDs": null,
                    "choice1": "A. Brave and caring",
                    "choice2": "B. Grateful and warm-hearted.",
                    "choice3": "C. Considerate and hardworking.",
                    "choice4": "D. Sympathetic and easy-going.",
                    "content": null,
                    "stuAnswer": null,
                    "aiComment": null,
                    "falseReason": null,
                    "userComment": null,
                    "sonExercise": null,
                    "cuoTiList": null,
                    "esID": null,
                    "single": false,
                    "existed": true
                },
                {
                    "id": 81,
                    "category": "yuedu",
                    "problem": "What message does the text mainly convey?",
                    "answer": "B",
                    "sonProID": null,
                    "score": 3,
                    "choiceNum": 4,
                    "level": 0,
                    "field": null,
                    "knowledgeIDs": null,
                    "choice1": "A. It's better to give than to receive.",
                    "choice2": "B. The blessed bear the heart of giving.",
                    "choice3": "C. Health matters much more than wealth.",
                    "choice4": "D. Volunteering makes the world a better place.",
                    "content": null,
                    "stuAnswer": null,
                    "aiComment": null,
                    "falseReason": null,
                    "userComment": null,
                    "sonExercise": null,
                    "cuoTiList": null,
                    "esID": null,
                    "single": false,
                    "existed": true
                }
            ],
            "cuoTiList": null,
            "esID": "dfe72ac2-0e2e-4e2f-930c-c5d80a0f4118",
            "single": false,
            "existed": true
        },
    {
            "id": 78,
            "category": "yuedu",
            "problem": "Why did Kaufman take about her memory in Paragraph 1?",
            "answer": "A",
            "sonProID": "79,80,81",
            "score": 3,
            "choiceNum": 4,
            "level": 0,
            "field": "医学",
            "knowledgeIDs": null,
            "choice1": "A. To illustrate the significance of life.",
            "choice2": "B. To recall her plain and boring days.",
            "choice3": "C. To indicate her motivation for paying back.",
            "choice4": "D. To confirm her enthusiasm for the profession.",
            "content": `Managing Your Emotions
    		
    What makes me angry? Mostly, I hate when someone tries to make someone else feel bad. I have to admit that once, when I was really angry, I actually called names. 
    
    I regretted doing this afterwards, but not full heartedly because I think I was provoked in that situation. The most positive way of dealing with anger is talking about the problem. I talk to someone who listens, or I'll write my thoughts down on paper. Learning how to deal with anger as you're growing up is so important. When you're younger, you might yell, or cry when you're angry, but as you get older,you're expected to handle your emotions much better. Learning to control your emotion now will prevent you from doing something that you'll regret later on in life!
    
    A bank robber stole a lot of money. He was caught and sent to prison, but the money was never found. When he came out of prison, they watched him to see what he would do. Here is the detective, reporting to the inspector. "Yes, sir, I found Johnny . I followed him all around the town, but frankly, I couldn't make anything out of what he bought. 
    
    Here's the list. "shirt , heavy crowbar, box of chocolates , shovel, heavy hammer, bunch of flowers .The inspector said, "Good. That helps me a lot. Do you remember how we watched him helping his neighbour, old Mrs. Judson to cover her backyard with cement?`,
            "stuAnswer": null,
            "aiComment": null,
            "falseReason": null,
            "userComment": null,
            "sonExercise": [
                {
                    "id": 78,
                    "category": null,
                    "problem": "Why did Kaufman take about her memory in Paragraph 1?",
                    "answer": "A",
                    "sonProID": null,
                    "score": 0,
                    "choiceNum": 4,
                    "level": 0,
                    "field": null,
                    "knowledgeIDs": null,
                    "choice1": "A. To illustrate the significance of life.",
                    "choice2": "B. To recall her plain and boring days.",
                    "choice3": "C. To indicate her motivation for paying back.",
                    "choice4": "D. To confirm her enthusiasm for the profession.",
                    "content": null,
                    "stuAnswer": null,
                    "aiComment": null,
                    "falseReason": null,
                    "userComment": null,
                    "sonExercise": null,
                    "cuoTiList": null,
                    "esID": null,
                    "single": false,
                    "existed": true
                },
                {
                    "id": 79,
                    "category": "yuedu",
                    "problem": "For a transplant patient, admission into the hospital requires the following EXCEPT",
                    "answer": "B",
                    "sonProID": null,
                    "score": 3,
                    "choiceNum": 4,
                    "level": 0,
                    "field": null,
                    "knowledgeIDs": null,
                    "choice1": "A. health insurance",
                    "choice2": "",
                    "choice3": "",
                    "choice4": "",
                    "content": null,
                    "stuAnswer": null,
                    "aiComment": null,
                    "falseReason": null,
                    "userComment": null,
                    "sonExercise": null,
                    "cuoTiList": null,
                    "esID": null,
                    "single": false,
                    "existed": true
                }
            ],
            "cuoTiList": null,
            "esID": "dfe72ac2-0e2e-4e2f-930c-c5d80a0f4118",
            "single": false,
            "existed": true
        },
    {
            "id": 78,
            "category": "yuedu",
            "problem": "Why did Kaufman take about her memory in Paragraph 1?",
            "answer": "A",
            "sonProID": "79,80,81",
            "score": 3,
            "choiceNum": 4,
            "level": 0,
            "field": "医学",
            "knowledgeIDs": null,
            "choice1": "A. To illustrate the significance of life.",
            "choice2": "B. To recall her plain and boring days.",
            "choice3": "C. To indicate her motivation for paying back.",
            "choice4": "D. To confirm her enthusiasm for the profession.",
            "content": `Managing Your Emotions
    		
    What makes me angry? Mostly, I hate when someone tries to make someone else feel bad. I have to admit that once, when I was really angry, I actually called names. 
    
    I regretted doing this afterwards, but not full heartedly because I think I was provoked in that situation. The most positive way of dealing with anger is talking about the problem. I talk to someone who listens, or I'll write my thoughts down on paper. Learning how to deal with anger as you're growing up is so important. When you're younger, you might yell, or cry when you're angry, but as you get older,you're expected to handle your emotions much better. Learning to control your emotion now will prevent you from doing something that you'll regret later on in life!
    
    A bank robber stole a lot of money. He was caught and sent to prison, but the money was never found. When he came out of prison, they watched him to see what he would do. Here is the detective, reporting to the inspector. "Yes, sir, I found Johnny . I followed him all around the town, but frankly, I couldn't make anything out of what he bought. 
    
    Here's the list. "shirt , heavy crowbar, box of chocolates , shovel, heavy hammer, bunch of flowers .The inspector said, "Good. That helps me a lot. Do you remember how we watched him helping his neighbour, old Mrs. Judson to cover her backyard with cement?`,
            "stuAnswer": null,
            "aiComment": null,
            "falseReason": null,
            "userComment": null,
            "sonExercise": [ 
                {
                    "id": 78,
                    "category": null,
                    "problem": "Why did Kaufman take about her memory in Paragraph 1?",
                    "answer": "A",
                    "sonProID": null,
                    "score": 0,
                    "choiceNum": 4,
                    "level": 0,
                    "field": null,
                    "knowledgeIDs": null,
                    "choice1": "A. To illustrate the significance of life.",
                    "choice2": "B. To recall her plain and boring days.",
                    "choice3": "C. To indicate her motivation for paying back.",
                    "choice4": "D. To confirm her enthusiasm for the profession.",
                    "content": null,
                    "stuAnswer": null,
                    "aiComment": null,
                    "falseReason": null,
                    "userComment": null,
                    "sonExercise": null,
                    "cuoTiList": null,
                    "esID": null,
                    "single": false,
                    "existed": true
                },
                {
                    "id": 79,
                    "category": "yuedu",
                    "problem": "For a transplant patient, admission into the hospital requires the following EXCEPT",
                    "answer": "B",
                    "sonProID": null,
                    "score": 3,
                    "choiceNum": 4,
                    "level": 0,
                    "field": null,
                    "knowledgeIDs": null,
                    "choice1": "A. health insurance",
                    "choice2": "",
                    "choice3": "",
                    "choice4": "",
                    "content": null,
                    "stuAnswer": null,
                    "aiComment": null,
                    "falseReason": null,
                    "userComment": null,
                    "sonExercise": null,
                    "cuoTiList": null,
                    "esID": null,
                    "single": false,
                    "existed": true
                }
            ],
            "cuoTiList": null,
            "esID": "dfe72ac2-0e2e-4e2f-930c-c5d80a0f4118",
            "single": false,
            "existed": true
        }
]

//选择题识别结果
export const tmpOCRResult2 = [
    {
        "id": 96,
        "category": "xuanze",
        "problem": "The professor walked onto the platform and seated himself in a chair, _ for answering questions.",
        "answer": "D",
        "sonProID": null,
        "score": 3,
        "choiceNum": 0,
        "stuID": null,
        "level": 0,
        "field": null,
        "knowledgeIDs": null,
        "choice1": "A.had prepared, This is a long sentense test, check my style! but but and and aaa cc",
        "choice2": "B.being prepared",
        "choice3": "C.preparing",
        "choice4": "D.prepared",
        "content": null,
        "stuAnswer": null,
        "aiComment": null,
        "falseReason": null,
        "userComment": null,
        "sonExercise": null,
        "cuoTiList": null,
        "esID": "db66338d-f10b-4e32-9471-57539766c298",
        "compCommentID": null,
        "transCommentID": null,
        "translateDetail": null,
        "compositionDetail": null,
        "isRight": false,
        "existed": true,
        "right": false,
        "single": false
    },
    {
        "id": 97,
        "category": "xuanze",
        "problem": "The professor walked onto the platform and seated himself in a chair, _ for answering questions.",
        "answer": "D",
        "sonProID": null,
        "score": 3,
        "choiceNum": 0,
        "stuID": null,
        "level": 0,
        "field": null,
        "knowledgeIDs": null,
        "choice1": "A.had prepared",
        "choice2": "B.being prepared",
        "choice3": "C.preparing",
        "choice4": "D.prepared",
        "content": null,
        "stuAnswer": null,
        "aiComment": null,
        "falseReason": null,
        "userComment": null,
        "sonExercise": null,
        "cuoTiList": null,
        "esID": "a39882ec-50e0-43bf-b8ee-d70e80bd4a12",
        "compCommentID": null,
        "transCommentID": null,
        "translateDetail": null,
        "compositionDetail": null,
        "isRight": false,
        "existed": true,
        "right": false,
        "single": false
    },
    {
        "id": 98,
        "category": "xuanze",
        "problem": "The professor walked onto the platform and seated himself in a chair, _ for answering questions.",
        "answer": "D",
        "sonProID": null,
        "score": 3,
        "choiceNum": 0,
        "stuID": null,
        "level": 0,
        "field": null,
        "knowledgeIDs": null,
        "choice1": "A.had prepared",
        "choice2": "B.being prepared",
        "choice3": "C.preparing",
        "choice4": "D.prepared",
        "content": null,
        "stuAnswer": null,
        "aiComment": null,
        "falseReason": null,
        "userComment": null,
        "sonExercise": null,
        "cuoTiList": null,
        "esID": "1da75ad0-02c1-466a-8724-73ba4ec7266d",
        "compCommentID": null,
        "transCommentID": null,
        "translateDetail": null,
        "compositionDetail": null,
        "isRight": false,
        "existed": true,
        "right": false,
        "single": false
    },
    {
        "id": null,
        "category": "xuanze",
        "problem": "The professor walked onto the platform and seated himself in a chair, ( ) for answering questions.",
        "answer": null,
        "sonProID": null,
        "score": 0,
        "choiceNum": 4,
        "stuID": null,
        "level": 0,
        "field": null,
        "knowledgeIDs": null,
        "choice1": "A、 had prepared",
        "choice2": "B、 being prepared",
        "choice3": "C、 preparing",
        "choice4": "D、 prepared",
        "content": null,
        "stuAnswer": "",
        "aiComment": "",
        "falseReason": null,
        "userComment": null,
        "sonExercise": null,
        "cuoTiList": null,
        "esID": "4c45f3cf-88f2-4496-94a3-40f0dda9fc44",
        "compCommentID": null,
        "transCommentID": null,
        "translateDetail": null,
        "compositionDetail": null,
        "isRight": false,
        "existed": true,
        "right": false,
        "single": false
    }
]

//作文识题结果
export const tmpOCRResult3 = [
    {
        "id": 90,
        "category": "zuowen",
        "problem": "",
        "answer": "In recent years, social media platforms have become an indispensable part of our daily lives, significantly influencing our communication, interaction, and perception of the world around us. On one hand, they facilitate instant connection and information sharing, fostering global awareness and social movements. For instance, social media played a crucial role in organizing protests and raising awareness about important social issues such as climate change and human rights violations.\r\n\r\nHowever, the pervasive use of social media also brings about negative consequences. It can lead to the spread of misinformation, cyberbullying, and addiction, affecting individuals' mental health and well-being. Moreover, social media platforms often prioritize sensational content over factual information, contributing to polarization and division within society.\r\n\r\nFurthermore, social media influences culture, politics, and interpersonal relationships. It shapes cultural trends, amplifies political discourse, and alters the dynamics of interpersonal connections. Yet, it can also lead to echo chambers and filter bubbles, limiting exposure to diverse perspectives.\r\n\r\nTo mitigate the negative impacts of social media, fostering digital literacy and critical thinking skills is crucial. Additionally, promoting responsible use and ethical practices by both users and platform providers can help create a healthier online environment. Emphasizing digital well-being and promoting meaningful interactions can maximize the benefits of social media while minimizing its drawbacks.",
        "sonProID": null,
        "score": 25,
        "choiceNum": 0,
        "level": 0,
        "field": "社会科学",
        "knowledgeIDs": null,
        "choice1": null,
        "choice2": null,
        "choice3": null,
        "choice4": null,
        "content": "近年来，社交媒体平台已成为我们日常生活中不可或缺的一部分，影响着我们的交流方式、互动方式以及对周围世界的认知。请就社交媒体对社会的各种影响展开讨论。考虑其正面和负面效应，并提供例证支持你的论点。此外，探讨社交媒体在塑造文化、政治、人际关系以及个体幸福感方面的作用。最后，讨论减轻负面影响、最大程度发挥社交媒体利益的潜在策略。请根据这个写出一篇关于社交媒体对社会的影响的议论文，不少于150字。",
        "stuAnswer": null,
        "aiComment": null,
        "falseReason": null,
        "userComment": null,
        "sonExercise": null,
        "cuoTiList": null,
        "esID": "58cb9eed-6347-4f7c-88a5-dce11d481dc9",
        "single": true,
        "existed": true
    },
    {
        "id": 91,
        "category": "zuowen",
        "problem": "",
        "answer": "In recent years, social media platforms have become an indispensable part of our daily lives, significantly influencing our communication, interaction, and perception of the world around us. On one hand, they facilitate instant connection and information sharing, fostering global awareness and social movements. For instance, social media played a crucial role in organizing protests and raising awareness about important social issues such as climate change and human rights violations.\r\n\r\nHowever, the pervasive use of social media also brings about negative consequences. It can lead to the spread of misinformation, cyberbullying, and addiction, affecting individuals' mental health and well-being. Moreover, social media platforms often prioritize sensational content over factual information, contributing to polarization and division within society.\r\n\r\nFurthermore, social media influences culture, politics, and interpersonal relationships. It shapes cultural trends, amplifies political discourse, and alters the dynamics of interpersonal connections. Yet, it can also lead to echo chambers and filter bubbles, limiting exposure to diverse perspectives.\r\n\r\nTo mitigate the negative impacts of social media, fostering digital literacy and critical thinking skills is crucial. Additionally, promoting responsible use and ethical practices by both users and platform providers can help create a healthier online environment. Emphasizing digital well-being and promoting meaningful interactions can maximize the benefits of social media while minimizing its drawbacks.",
        "sonProID": null,
        "score": 25,
        "choiceNum": 0,
        "level": 0,
        "field": "社会科学",
        "knowledgeIDs": null,
        "choice1": null,
        "choice2": null,
        "choice3": null,
        "choice4": null,
        "content": "近年来，社交媒体平台已成为我们日常生活中不可或缺的一部分，影响着我们的交流方式、互动方式以及对周围世界的认知。请就社交媒体对社会的各种影响展开讨论。考虑其正面和负面效应，并提供例证支持你的论点。此外，探讨社交媒体在塑造文化、政治、人际关系以及个体幸福感方面的作用。最后，讨论减轻负面影响、最大程度发挥社交媒体利益的潜在策略。请根据这个写出一篇关于社交媒体对社会的影响的议论文，不少于150字。",
        "stuAnswer": null,
        "aiComment": null,
        "falseReason": null,
        "userComment": null,
        "sonExercise": null,
        "cuoTiList": null,
        "esID": "286c0b77-6094-4911-8499-28c6151676bb",
        "single": true,
        "existed": true
    },
    {
        "id": 92,
        "category": "zuowen",
        "problem": "",
        "answer": "In recent years, social media platforms have become an indispensable part of our daily lives, significantly influencing our communication, interaction, and perception of the world around us. On one hand, they facilitate instant connection and information sharing, fostering global awareness and social movements. For instance, social media played a crucial role in organizing protests and raising awareness about important social issues such as climate change and human rights violations.\r\n\r\nHowever, the pervasive use of social media also brings about negative consequences. It can lead to the spread of misinformation, cyberbullying, and addiction, affecting individuals' mental health and well-being. Moreover, social media platforms often prioritize sensational content over factual information, contributing to polarization and division within society.\r\n\r\nFurthermore, social media influences culture, politics, and interpersonal relationships. It shapes cultural trends, amplifies political discourse, and alters the dynamics of interpersonal connections. Yet, it can also lead to echo chambers and filter bubbles, limiting exposure to diverse perspectives.\r\n\r\nTo mitigate the negative impacts of social media, fostering digital literacy and critical thinking skills is crucial. Additionally, promoting responsible use and ethical practices by both users and platform providers can help create a healthier online environment. Emphasizing digital well-being and promoting meaningful interactions can maximize the benefits of social media while minimizing its drawbacks.",
        "sonProID": null,
        "score": 25,
        "choiceNum": 0,
        "level": 0,
        "field": "社会科学",
        "knowledgeIDs": null,
        "choice1": null,
        "choice2": null,
        "choice3": null,
        "choice4": null,
        "content": "近年来，社交媒体平台已成为我们日常生活中不可或缺的一部分，影响着我们的交流方式、互动方式以及对周围世界的认知。请就社交媒体对社会的各种影响展开讨论。考虑其正面和负面效应，并提供例证支持你的论点。此外，探讨社交媒体在塑造文化、政治、人际关系以及个体幸福感方面的作用。最后，讨论减轻负面影响、最大程度发挥社交媒体利益的潜在策略。请根据这个写出一篇关于社交媒体对社会的影响的议论文，不少于150字。",
        "stuAnswer": null,
        "aiComment": null,
        "falseReason": null,
        "userComment": null,
        "sonExercise": null,
        "cuoTiList": null,
        "esID": "60bc886e-2dbd-4682-9e75-d18c3bdda4f3",
        "single": true,
        "existed": true
    },
    {
        "id": null,
        "category": "zuowen",
        "problem": null,
        "answer": null,
        "sonProID": null,
        "score": 0,
        "choiceNum": 0,
        "level": 0,
        "field": "社交媒体",
        "knowledgeIDs": null,
        "choice1": null,
        "choice2": null,
        "choice3": null,
        "choice4": null,
        "content": " 作文题目：《社交媒体对社会的影响》\n  近年来，社交媒体平台已成为我们日常生活中不可或缺的一部分，影响着我们的交流方式、互动方 式以及对周围世界的认知。请就社交媒体对社会的各种影响展开讨论。考虑其正面和负面效应，并 提供例证支持你的论点。此外，探讨社交媒体在塑造文化、政治、人际关系以及个体幸福感方面的 作用。最后，讨论减轻负面影响、最大程度发挥社交媒体利益的潜在策略。\n  ",
        "stuAnswer": "",
        "aiComment": "",
        "falseReason": null,
        "userComment": null,
        "sonExercise": null,
        "cuoTiList": null,
        "esID": "fec386f7-8922-473c-8cee-c10aa3a9aed6",
        "single": false,
        "existed": true
    }
]

//翻译识别结果
export const tmpOCRResult4 = [
    {
        "id": 93,
        "category": "fanyi",
        "problem": null,
        "answer": "人工智能（AI）正在迅速改变我们生活的各个方面，从医疗保健和金融到交通和娱乐。借助AI，机器能够执行传统上需要人类智慧的任务，比如识别语音、解释图像和做出决策。随着AI技术的不断发展，它有潜力彻底改变行业，并以无数种方式提高效率。然而，AI也引发了一些重要的伦理和社会问题，比如对工作岗位的置换担忧、隐私问题以及算法偏见。因此，对决策者、研究人员和公众来说，参与关于AI负责任的发展和使用的讨论至关重要，以确保最大限度地发挥其好处，同时尽量减少潜在风险。",
        "sonProID": null,
        "score": 15,
        "stuScore": 0,
        "choiceNum": 0,
        "stuID": null,
        "level": 0,
        "field": "科技",
        "knowledgeIDs": null,
        "choice1": null,
        "choice2": null,
        "choice3": null,
        "choice4": null,
        "content": "题目：请将以下长文本翻译成中文：\r\n\r\n\"Artificial intelligence (AI) is rapidly transforming various aspects of our lives, from healthcare and finance to transportation and entertainment. With AI, machines are able to perform tasks that traditionally required human intelligence, such as recognizing speech, interpreting images, and making decisions. As AI technology continues to advance, it has the potential to revolutionize industries and improve efficiency in countless ways. However, AI also raises important ethical and societal questions, such as concerns about job displacement, privacy, and algorithmic bias. Therefore, it is crucial for policymakers, researchers, and the public to engage in discussions about the responsible development and use of AI to ensure that its benefits are maximized while minimizing potential risks.\"",
        "stuAnswer": null,
        "aiComment": null,
        "falseReason": null,
        "userComment": null,
        "sonExercise": null,
        "cuoTiList": null,
        "esID": "84a1f293-de10-408b-b08f-11a8479f55a0",
        "compCommentID": null,
        "transCommentID": null,
        "translateDetail": null,
        "compositionDetail": null,
        "isRight": false,
        "right": false,
        "single": false,
        "existed": true
    },
    {
        "id": 94,
        "category": "fanyi",
        "problem": null,
        "answer": "人工智能（AI）正在迅速改变我们生活的各个方面，从医疗保健和金融到交通和娱乐。借助AI，机器能够执行传统上需要人类智慧的任务，比如识别语音、解释图像和做出决策。随着AI技术的不断发展，它有潜力彻底改变行业，并以无数种方式提高效率。然而，AI也引发了一些重要的伦理和社会问题，比如对工作岗位的置换担忧、隐私问题以及算法偏见。因此，对决策者、研究人员和公众来说，参与关于AI负责任的发展和使用的讨论至关重要，以确保最大限度地发挥其好处，同时尽量减少潜在风险。",
        "sonProID": null,
        "score": 15,
        "stuScore": 0,
        "choiceNum": 0,
        "stuID": null,
        "level": 0,
        "field": "科技",
        "knowledgeIDs": null,
        "choice1": null,
        "choice2": null,
        "choice3": null,
        "choice4": null,
        "content": "题目：请将以下长文本翻译成中文：\r\n\r\n\"Artificial intelligence (AI) is rapidly transforming various aspects of our lives, from healthcare and finance to transportation and entertainment. With AI, machines are able to perform tasks that traditionally required human intelligence, such as recognizing speech, interpreting images, and making decisions. As AI technology continues to advance, it has the potential to revolutionize industries and improve efficiency in countless ways. However, AI also raises important ethical and societal questions, such as concerns about job displacement, privacy, and algorithmic bias. Therefore, it is crucial for policymakers, researchers, and the public to engage in discussions about the responsible development and use of AI to ensure that its benefits are maximized while minimizing potential risks.\"",
        "stuAnswer": null,
        "aiComment": null,
        "falseReason": null,
        "userComment": null,
        "sonExercise": null,
        "cuoTiList": null,
        "esID": "224362cf-f963-4143-b97c-a3899a5a164e",
        "compCommentID": null,
        "transCommentID": null,
        "translateDetail": null,
        "compositionDetail": null,
        "isRight": false,
        "right": false,
        "single": false,
        "existed": true
    },
    {
        "id": 95,
        "category": "fanyi",
        "problem": null,
        "answer": "人工智能（AI）正在迅速改变我们生活的各个方面，从医疗保健和金融到交通和娱乐。借助AI，机器能够执行传统上需要人类智慧的任务，比如识别语音、解释图像和做出决策。随着AI技术的不断发展，它有潜力彻底改变行业，并以无数种方式提高效率。然而，AI也引发了一些重要的伦理和社会问题，比如对工作岗位的置换担忧、隐私问题以及算法偏见。因此，对决策者、研究人员和公众来说，参与关于AI负责任的发展和使用的讨论至关重要，以确保最大限度地发挥其好处，同时尽量减少潜在风险。",
        "sonProID": null,
        "score": 15,
        "stuScore": 0,
        "choiceNum": 0,
        "stuID": null,
        "level": 0,
        "field": "科技",
        "knowledgeIDs": null,
        "choice1": null,
        "choice2": null,
        "choice3": null,
        "choice4": null,
        "content": "题目：请将以下长文本翻译成中文：\r\n\r\n\"Artificial intelligence (AI) is rapidly transforming various aspects of our lives, from healthcare and finance to transportation and entertainment. With AI, machines are able to perform tasks that traditionally required human intelligence, such as recognizing speech, interpreting images, and making decisions. As AI technology continues to advance, it has the potential to revolutionize industries and improve efficiency in countless ways. However, AI also raises important ethical and societal questions, such as concerns about job displacement, privacy, and algorithmic bias. Therefore, it is crucial for policymakers, researchers, and the public to engage in discussions about the responsible development and use of AI to ensure that its benefits are maximized while minimizing potential risks.\"",
        "stuAnswer": null,
        "aiComment": null,
        "falseReason": null,
        "userComment": null,
        "sonExercise": null,
        "cuoTiList": null,
        "esID": "5bf027c6-c494-4383-9af9-29f0150e8844",
        "compCommentID": null,
        "transCommentID": null,
        "translateDetail": null,
        "compositionDetail": null,
        "isRight": false,
        "right": false,
        "single": false,
        "existed": true
    },
    {
        "id": null,
        "category": "fanyi",
        "problem": null,
        "answer": null,
        "sonProID": null,
        "score": 0,
        "stuScore": 0,
        "choiceNum": 0,
        "stuID": null,
        "level": 0,
        "field": "科技",
        "knowledgeIDs": null,
        "choice1": null,
        "choice2": null,
        "choice3": null,
        "choice4": null,
        "content": " 题目：请将以下长文本翻译成中文：\n  \"Artificial intelligence (Al) is rapidly transforming various aspects of our lives, from healthcare and finance to transportation and entertainment. With Al, machines are able to perform tasks that traditionally required human intelligence, such as recognizing speech, interpreting images, and making decisions. As Al technology continues to advance, it has the potential to revolutionize industries and improve efficiency in countless ways. However, Al also raises important ethical and societal questions, such as concerns about job displacement, privacy, and algorithmic bias.\n  Therefore, it is crucial for policymakers, researchers, and the public to engage in discussions about the responsible development and use of Al to ensure that its benefits are maximized while minimizing potential risks.\"\n  ",
        "stuAnswer": "",
        "aiComment": "",
        "falseReason": null,
        "userComment": null,
        "sonExercise": null,
        "cuoTiList": null,
        "esID": "27b83931-16bc-4a61-a040-2a861f506285",
        "compCommentID": null,
        "transCommentID": null,
        "translateDetail": null,
        "compositionDetail": null,
        "isRight": false,
        "right": false,
        "single": false,
        "existed": true
    }
]

